_wandb:
    value:
        cli_version: 0.21.0
        e:
            3poqhg33wyz09klmpg6qwhsd5e2ygcbp:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "804232626176"
                        used: "354065735680"
                email: melihak635442@gmail.com
                executable: /home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/bin/python
                git:
                    commit: ebea5488bf0aeb4d8d97a4896ffd27621333b6f9
                    remote: git@github.com:m24ih/Bites_CPU_Analizi.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-1fcb879c-ca2f-354a-24bb-c9dd6765cc0b
                host: CachyOS
                memory:
                    total: "41390157824"
                os: Linux-6.15.7-3-cachyos-x86_64-with-glibc2.41
                program: /home/melih/Downloads/transformer-wandb.py
                python: CPython 3.13.5
                root: /home/melih/Documents/Bites_CPU_Analizi
                startedAt: "2025-07-30T17:27:15.872358Z"
                writerId: 3poqhg33wyz09klmpg6qwhsd5e2ygcbp
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 64
d_model:
    value: 256
device:
    value: cuda
dim_feedforward:
    value: 1024
epochs:
    value: 15
input_dim:
    value: 64
lr:
    value: 0.0001
nhead:
    value: 8
num_classes:
    value: 10
num_encoder_layers:
    value: 3
