_wandb:
    value:
        cli_version: 0.21.0
        e:
            t41m8rzwhgt4uhj8r0ddh9xkd5xnklh3:
                codePath: 3.1_Tespit_Wandb.ipynb
                codePathLocal: 3.1_Tespit_Wandb.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "804232626176"
                        used: "354478964736"
                email: melihak635442@gmail.com
                executable: /home/melih/Documents/Bites_CPU_Analizi/bites_cpu_venv/bin/python
                git:
                    commit: b63a9f2764e41cda00823afd5147b3e34bbd35fb
                    remote: git@github.com:m24ih/Bites_CPU_Analizi.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-1fcb879c-ca2f-354a-24bb-c9dd6765cc0b
                host: CachyOS
                memory:
                    total: "41390153728"
                os: Linux-6.15.7-3-cachyos-x86_64-with-glibc2.41
                program: /home/melih/Documents/Bites_CPU_Analizi/3.1_Tespit_Wandb.ipynb
                python: CPython 3.13.5
                root: /home/melih/Documents/Bites_CPU_Analizi
                startedAt: "2025-07-31T11:18:49.918953Z"
                writerId: t41m8rzwhgt4uhj8r0ddh9xkd5xnklh3
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "8":
                - 1
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
        visualize:
            conf_mat:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: conf_mat_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
max_depth:
    value: 5
model_type:
    value: DecisionTree
